### ISSUE TITLE
Improve PWA with lighthouse

### ISSUE THREAD

**Issue by LegacyDebaditya** [shubhamV123/ydkjs-documentation#1]
Here is how you can increase your pwa experience with lighthouse.
![Capture](https://user-images.githubusercontent.com/63513685/100058956-44b66e80-2e50-11eb-94ab-268b9db75c7e.JPG)
Go to lighthouse and check out your results,also you can see the results above.

**Comment by shubhamV123** [comment]
Hi Thanks for opening this issue. Yes this is something I need to fix. Will fix when add more content. If it's critical and you know how to fix it. Feel free to raise **PR**

**Comment by shubhamV123** [comment]
Added your code and merged in master.
